spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.33.249.188/db_crm?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
      username: root
      password: root
  redis:
    host: 101.33.249.188
    port: 6379
    database: 2
    password: root
logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
server:
  port: 8082

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.ag.crm.domain

qiniu:
  accessKey: sXkbVeCyXjnRVwEsR2nt_ghjI0lTAWkunRrapBgV
  accessSecretKey: 9gG43y9GgCWEnp5db5-JjUFA577sB29zCu3BXsDs

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

