package com.ag.crm.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class CusDevPlan {

    private Integer id;

    private Integer saleChanceId;

    private String planItem;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd") // 如果传递的参数是Date类型，要求传入的时间字符串的格式
    private Date planDate;

    private String exeAffect;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createDate;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateDate;

    private Integer isValid;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSaleChanceId() {
        return saleChanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.sale_chance_id
     *
     * @param saleChanceId the value for t_cus_dev_plan.sale_chance_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setSaleChanceId(Integer saleChanceId) {
        this.saleChanceId = saleChanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.plan_item
     *
     * @return the value of t_cus_dev_plan.plan_item
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getPlanItem() {
        return planItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.plan_item
     *
     * @param planItem the value for t_cus_dev_plan.plan_item
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setPlanItem(String planItem) {
        this.planItem = planItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.plan_date
     *
     * @return the value of t_cus_dev_plan.plan_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getPlanDate() {
        return planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.plan_date
     *
     * @param planDate the value for t_cus_dev_plan.plan_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setPlanDate(Date planDate) {
        this.planDate = planDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.exe_affect
     *
     * @return the value of t_cus_dev_plan.exe_affect
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getExeAffect() {
        return exeAffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.exe_affect
     *
     * @param exeAffect the value for t_cus_dev_plan.exe_affect
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setExeAffect(String exeAffect) {
        this.exeAffect = exeAffect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.create_date
     *
     * @return the value of t_cus_dev_plan.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.create_date
     *
     * @param createDate the value for t_cus_dev_plan.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.update_date
     *
     * @return the value of t_cus_dev_plan.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.update_date
     *
     * @param updateDate the value for t_cus_dev_plan.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cus_dev_plan.is_valid
     *
     * @return the value of t_cus_dev_plan.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cus_dev_plan.is_valid
     *
     * @param isValid the value for t_cus_dev_plan.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}
