package com.ag.crm.domain;

import java.util.Date;

public class CustomerOrder {

    private Integer id;

    private Integer cusId;

    private String orderNo;

    private Date orderDate;

    private String address;

    private Integer state;

    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_order.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_order.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.id
     *
     * @return the value of t_customer_order.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.id
     *
     * @param id the value for t_customer_order.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.cus_id
     *
     * @return the value of t_customer_order.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.cus_id
     *
     * @param cusId the value for t_customer_order.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.order_no
     *
     * @return the value of t_customer_order.order_no
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.order_no
     *
     * @param orderNo the value for t_customer_order.order_no
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.order_date
     *
     * @return the value of t_customer_order.order_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.order_date
     *
     * @param orderDate the value for t_customer_order.order_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.address
     *
     * @return the value of t_customer_order.address
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.address
     *
     * @param address the value for t_customer_order.address
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.state
     *
     * @return the value of t_customer_order.state
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.state
     *
     * @param state the value for t_customer_order.state
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.create_date
     *
     * @return the value of t_customer_order.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.create_date
     *
     * @param createDate the value for t_customer_order.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.update_date
     *
     * @return the value of t_customer_order.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.update_date
     *
     * @param updateDate the value for t_customer_order.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_order.is_valid
     *
     * @return the value of t_customer_order.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_order.is_valid
     *
     * @param isValid the value for t_customer_order.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}
