package com.ag.crm.domain;

import java.util.Date;

public class CustomerLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Integer cusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.link_name
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private String linkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.sex
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.zhiwei
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private String zhiwei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.office_phone
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private String officePhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.phone
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.ceate_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Date ceateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer_linkman.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.id
     *
     * @return the value of t_customer_linkman.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.id
     *
     * @param id the value for t_customer_linkman.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.cus_id
     *
     * @return the value of t_customer_linkman.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.cus_id
     *
     * @param cusId the value for t_customer_linkman.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.link_name
     *
     * @return the value of t_customer_linkman.link_name
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.link_name
     *
     * @param linkName the value for t_customer_linkman.link_name
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setLinkName(String linkName) {
        this.linkName = linkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.sex
     *
     * @return the value of t_customer_linkman.sex
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.sex
     *
     * @param sex the value for t_customer_linkman.sex
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.zhiwei
     *
     * @return the value of t_customer_linkman.zhiwei
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getZhiwei() {
        return zhiwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.zhiwei
     *
     * @param zhiwei the value for t_customer_linkman.zhiwei
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setZhiwei(String zhiwei) {
        this.zhiwei = zhiwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.office_phone
     *
     * @return the value of t_customer_linkman.office_phone
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getOfficePhone() {
        return officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.office_phone
     *
     * @param officePhone the value for t_customer_linkman.office_phone
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setOfficePhone(String officePhone) {
        this.officePhone = officePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.phone
     *
     * @return the value of t_customer_linkman.phone
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.phone
     *
     * @param phone the value for t_customer_linkman.phone
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.is_valid
     *
     * @return the value of t_customer_linkman.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.is_valid
     *
     * @param isValid the value for t_customer_linkman.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.ceate_date
     *
     * @return the value of t_customer_linkman.ceate_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getCeateDate() {
        return ceateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.ceate_date
     *
     * @param ceateDate the value for t_customer_linkman.ceate_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCeateDate(Date ceateDate) {
        this.ceateDate = ceateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_linkman.update_date
     *
     * @return the value of t_customer_linkman.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_linkman.update_date
     *
     * @param updateDate the value for t_customer_linkman.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}
