package com.ag.crm.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CustomerContact {

    private Integer id;

    private Integer cusId;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date contactTime;

    private String address;

    private String overview;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createDate;
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateDate;

    private Integer isValid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.id
     *
     * @return the value of t_customer_contact.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.id
     *
     * @param id the value for t_customer_contact.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.cus_id
     *
     * @return the value of t_customer_contact.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getCusId() {
        return cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.cus_id
     *
     * @param cusId the value for t_customer_contact.cus_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCusId(Integer cusId) {
        this.cusId = cusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.contact_time
     *
     * @return the value of t_customer_contact.contact_time
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getContactTime() {
        return contactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.contact_time
     *
     * @param contactTime the value for t_customer_contact.contact_time
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setContactTime(Date contactTime) {
        this.contactTime = contactTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.address
     *
     * @return the value of t_customer_contact.address
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.address
     *
     * @param address the value for t_customer_contact.address
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.overview
     *
     * @return the value of t_customer_contact.overview
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.overview
     *
     * @param overview the value for t_customer_contact.overview
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setOverview(String overview) {
        this.overview = overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.create_date
     *
     * @return the value of t_customer_contact.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.create_date
     *
     * @param createDate the value for t_customer_contact.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.update_date
     *
     * @return the value of t_customer_contact.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.update_date
     *
     * @param updateDate the value for t_customer_contact.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_contact.is_valid
     *
     * @return the value of t_customer_contact.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_contact.is_valid
     *
     * @param isValid the value for t_customer_contact.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }
}
