package com.ag.crm.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class CustomerReprieve {

    private Integer id;

    private Integer lossId;

    private String measure;

    private Integer isValid;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createDate;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date updateDate;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_reprieve.id
     *
     * @param id the value for t_customer_reprieve.id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_reprieve.loss_id
     *
     * @return the value of t_customer_reprieve.loss_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getLossId() {
        return lossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_reprieve.loss_id
     *
     * @param lossId the value for t_customer_reprieve.loss_id
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setLossId(Integer lossId) {
        this.lossId = lossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_reprieve.measure
     *
     * @return the value of t_customer_reprieve.measure
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_reprieve.measure
     *
     * @param measure the value for t_customer_reprieve.measure
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setMeasure(String measure) {
        this.measure = measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_reprieve.is_valid
     *
     * @return the value of t_customer_reprieve.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_reprieve.is_valid
     *
     * @param isValid the value for t_customer_reprieve.is_valid
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_reprieve.create_date
     *
     * @return the value of t_customer_reprieve.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_reprieve.create_date
     *
     * @param createDate the value for t_customer_reprieve.create_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer_reprieve.update_date
     *
     * @return the value of t_customer_reprieve.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer_reprieve.update_date
     *
     * @param updateDate the value for t_customer_reprieve.update_date
     *
     * @mbg.generated Wed Jun 15 17:09:56 CST 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}
