package com.ag.crm.dao;

import com.ag.crm.domain.CustomerContact;
import java.util.List;

public interface CustomerContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int insert(CustomerContact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    CustomerContact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    List<CustomerContact> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_contact
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int updateByPrimaryKey(CustomerContact record);

    List<CustomerContact> selectByCId(Integer cId, int start, Integer pageSize);

    int selectCount(Integer cId);
}
