package com.ag.crm.dao;

import com.ag.crm.domain.CustomerReprieve;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerReprieveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_reprieve
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_reprieve
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int insert(CustomerReprieve record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_reprieve
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    CustomerReprieve selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_reprieve
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    List<CustomerReprieve> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_reprieve
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int updateByPrimaryKey(CustomerReprieve record);

    List<CustomerReprieve> selectByLossId(@Param("lossId") Integer lossId,@Param("start") Integer start,@Param("pageSize") Integer pageSize);

    int selectCount(Integer lossId);

    Integer updateByPrimaryKeySelective(CustomerReprieve customerReprieve);
}
