package com.ag.crm.dao;

import com.ag.crm.domain.CusDevPlan;
import com.ag.crm.domain.Customer;
import com.ag.crm.domain.CustomerDTO;
import com.ag.crm.domain.CustomerVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int insert(CustomerVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int updateByPrimaryKey(CustomerVO record);


    List<Customer> selectByParams(@Param("customer") CustomerVO customer, @Param("start") int start, @Param("pageSize") Integer pageSize);

    int selectCountByParams(CustomerVO customer);
    int selectCountByParams2(CustomerDTO customer);

    List<Map> selectCustomerContributionByParams(CustomerDTO customerDTO);

    List<Map<String,Object>> countCustomerMake();

    String selectUsernameByCusNo(String cusNo);

    Integer selectCusManagerByCusNo(String cusNo);

    Customer selectByCName(String customer);

    List<Customer> queryLossCustomers();

    int updateCustomerStateByIds(List<Integer> lossCustomerIds);

    int insertCustomer(Customer customer);

    int selectIdByKhno(String khno);
}
