package com.ag.crm.dao;

import com.ag.crm.domain.CustomerLinkman;
import java.util.List;

public interface CustomerLinkmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_linkman
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_linkman
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int insert(CustomerLinkman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_linkman
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    CustomerLinkman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_linkman
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    List<CustomerLinkman> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_linkman
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int updateByPrimaryKey(CustomerLinkman record);

    List<CustomerLinkman> selectByCId(Integer cId);
}
