package com.ag.crm.dao;

import com.ag.crm.domain.CustomerOrder;
import java.util.List;

public interface CustomerOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_order
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_order
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int insert(CustomerOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_order
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    CustomerOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_order
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    List<CustomerOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_order
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int updateByPrimaryKey(CustomerOrder record);


    int selectCountByParams(Integer cId);

    List<CustomerOrder> selectCOrderById(Integer cId, int start, Integer pageSize);

    CustomerOrder queryLossCustomerOrderByCustomerId(Integer id);

    int selectIdByONo(String orderNo);
}
