package com.ag.crm.dao;

import com.ag.crm.domain.*;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CustomerServeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_serve
     *
     * @mbg.generated Mon Jun 20 19:47:58 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_serve
     *
     * @mbg.generated Mon Jun 20 19:47:58 CST 2022
     */
    int insert(CustomerServe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_serve
     *
     * @mbg.generated Mon Jun 20 19:47:58 CST 2022
     */
    CustomerServe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_serve
     *
     * @mbg.generated Mon Jun 20 19:47:58 CST 2022
     */
    List<CustomerServe> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer_serve
     *
     * @mbg.generated Mon Jun 20 19:47:58 CST 2022
     */
    int updateByPrimaryKey(CustomerServe record);

    List<CustomerServe> selectByParams(CustomerServeDTO customerServeDTO);

    int selectCount(CustomerServeDTO customerServeDTO);

    Integer insertCustomerServe(CustomerServe customerServe);

    Integer updateByPrimaryKeySelective(CustomerServe customerServe);

    List<CustomerServe> selectByPage(@Param("start") int start,@Param("pageSize") Integer pageSize);

    int selectAllCount();
}
