package com.ag.crm.dao;

import com.ag.crm.domain.Datadic;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DatadicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int insert(Datadic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    Datadic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    List<Datadic> selectAll(@Param("start") Integer start,@Param("pageSize") Integer pageSize);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_datadic
     *
     * @mbg.generated Wed Jun 15 17:10:54 CST 2022
     */
    int updateByPrimaryKey(Datadic record);

    Datadic selectBydataDicValue(String level);

    Datadic selectByNameAndValue(String dataDicName, String dataDicValue);

    int updateById(Datadic datadic);

    int selectCount();
}
